# Generated by Django 6.0.2 on 2026-02-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Human-readable address', max_length=500),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='When the job should be done (null = ASAP)', null=True),
        ),
    ]
