# Generated by Django 6.0.2 on 2026-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicejob_address_servicejob_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='category',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Cleaning', 'Cleaning'), ('HVAC', 'HVAC'), ('Carpentry', 'Carpentry'), ('Mechanic', 'Mechanic'), ('Housekeeping', 'Housekeeping'), ('Guard', 'Guard / Security'), ('Packing', 'Packing / Moving'), ('AC Repair', 'AC Repair'), ('Painting', 'Painting'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
