# Generated by Django 6.0.2 on 2026-02-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.servicejob'),
        ),
    ]
