# Generated by Django 6.0.2 on 2026-02-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Job Provider', 'Job Provider'), ('Both', 'Both')], default='Job Provider', max_length=20),
        ),
    ]
