# Generated by Django 6.0.2 on 2026-02-22 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_user_type_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhaar_number',
            field=models.BigIntegerField(blank=True, help_text='12-digit Aadhaar Number', null=True, validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Must match government ID.', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Toggle: 'Available Now' vs 'Busy'"),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, help_text="e.g., 'Python Developer', 'House Guard'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='live_location',
            field=models.JSONField(blank=True, help_text='For Map/3D globe pins', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, help_text='Essential for OTP', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_category',
            field=models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Skilled Trade', 'Skilled Trade'), ('General Labor', 'General Labor')], max_length=50, null=True),
        ),
    ]
