# Generated by Django 6.0.2 on 2026-02-23 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, help_text='Average rating 0-5', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of work experience', null=True),
        ),
    ]
