# Generated by Django 6.0.2 on 2026-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_rating_profile_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Worker', 'Worker'), ('Job Provider', 'Job Provider')], default='Job Provider', max_length=20),
        ),
    ]
