# Generated by Django 6.0.2 on 2026-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
